/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RentDraft;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author giana
 */
public class Main extends javax.swing.JFrame {

    private MySqlClass mySQL = new MySqlClass();
    private ArrayList<Car> cars;
    DefaultTableModel model;
    
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        AddButtonMain = new javax.swing.JButton();
        RentButtonMain = new javax.swing.JButton();
        searchByBrandButton = new javax.swing.JButton();
        searchByModelButton = new javax.swing.JButton();
        searchByPriceRangeButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "License Plate", "Brand", "Model", "Price", "Description", "Date Rented", "Rent Until", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Rental Management System");

        AddButtonMain.setText("Add Car");
        AddButtonMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonMainActionPerformed(evt);
            }
        });

        RentButtonMain.setText("Rent Car");
        RentButtonMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentButtonMainActionPerformed(evt);
            }
        });

        searchByBrandButton.setText("Search by Brand");
        searchByBrandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByBrandButtonActionPerformed(evt);
            }
        });

        searchByModelButton.setText("Search by Model");
        searchByModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByModelButtonActionPerformed(evt);
            }
        });

        searchByPriceRangeButton.setText("Search by Price Range");
        searchByPriceRangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByPriceRangeButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddButtonMain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RentButtonMain)
                        .addGap(52, 52, 52)
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(searchByBrandButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchByModelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchByPriceRangeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButtonMain)
                    .addComponent(RentButtonMain)
                    .addComponent(searchByBrandButton)
                    .addComponent(searchByModelButton)
                    .addComponent(searchByPriceRangeButton)
                    .addComponent(updateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonMainActionPerformed
        // TODO add your handling code here:
        AddCar addcarframe = new AddCar();
        addcarframe.setVisible(true);
        
    }//GEN-LAST:event_AddButtonMainActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        clearTable();
        updateTable();
    }//GEN-LAST:event_formWindowOpened

    private void searchByBrandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByBrandButtonActionPerformed
        SearchByBrand SBB = new SearchByBrand();
        SBB.setVisible(true);
    }//GEN-LAST:event_searchByBrandButtonActionPerformed

    private void searchByModelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByModelButtonActionPerformed
        SearchByModel SBM = new SearchByModel();
        SBM.setVisible(true);
    }//GEN-LAST:event_searchByModelButtonActionPerformed

    private void searchByPriceRangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByPriceRangeButtonActionPerformed
        SearchByPriceRange SBPM = new SearchByPriceRange();
        SBPM.setVisible(true);
    }//GEN-LAST:event_searchByPriceRangeButtonActionPerformed

    private void RentButtonMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentButtonMainActionPerformed
        // TODO add your handling code here:
        RentCar rentcarframe = new RentCar();
        rentcarframe.setVisible(true);
    }//GEN-LAST:event_RentButtonMainActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        clearTable();
        updateTable();
    }//GEN-LAST:event_updateButtonActionPerformed

    public void clearTable()
    {
        model=(DefaultTableModel) jTable1.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged(); // notifies the JTable that the model has changed
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    public void updateTable(){
        clearTable();
        cars = mySQL.ShowTable();
        model = (DefaultTableModel) jTable1.getModel();
        for(Car c: cars){   
            Date currentDate = new Date();
            SimpleDateFormat fm1 = new SimpleDateFormat("yyyy-MM-dd");
            String startDateRaw = (String) c.getDateRented();
            String endDateRaw = (String) c.getRentUntil();
            String status = null;
            if(startDateRaw != null || endDateRaw != null){
                 try {
                     Date startDate = fm1.parse(startDateRaw);
                     Date endDate = fm1.parse(endDateRaw);
                     if(currentDate.before(startDate)){
                     status = "Booked";
                     } else if(currentDate.before(endDate)){
                         status = "Out";
                     } else {
                         status = "Available";
                     }
                 } catch (ParseException ex) {
                     Logger.getLogger(RentCar.class.getName()).log(Level.SEVERE, null, ex);
                 }
            } else {
                 status = "Available";
            }
            model.addRow(new Object[] {c.getLicensePlate(), c.getBrand(), c.getModel(), c.getPrice(), c.getDescription(), c.getDateRented(), c.getRentUntil(), status});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButtonMain;
    private javax.swing.JButton RentButtonMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton searchByBrandButton;
    private javax.swing.JButton searchByModelButton;
    private javax.swing.JButton searchByPriceRangeButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
